"""Add PostGIS location to Doctor

Revision ID: 49b3700a14eb
Revises: fb25a835c194
Create Date: 2026-09-18 04:45:12.055737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '49b3700a14eb'
down_revision: Union[str, Sequence[str], None] = 'fb25a835c194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.drop_column('doctors', 'location_lat')
    op.drop_column('doctors', 'location_lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('location_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('location_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('doctors', 'location')
    # ### end Alembic commands ###
